version: "3.9"

services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
    environment:
      LIVEKIT_CONFIG: |
        port: 7880
        rtc:
          tcp_port: 7881
        keys:
          ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
        development: true
    restart: unless-stopped
    networks:
      - zypherus-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env.local
    ports:
      - "4000:4000"
      - "4300:4300"
    depends_on:
      - livekit
    restart: unless-stopped
    networks:
      - zypherus-network

networks:
  zypherus-network:
    driver: bridge
